### PR TITLE
Fix incorrect s3fs config in settings.php for prod and stage [ch1139]

### PR DESCRIPTION
**Pull request by joesb**

### CODE REVIEW

**Comment by stutily** [comment]
@joesb Does s3fs works ok if configured correctly ?

**Comment by joesb** [comment]
So these configuration changes (added manually on prod for now — to check they work) do now allow Connect to connect to  S3 for s3fs. But now the 'validation' tool in the s3fs module now gives this error message:

Screenshot 2019-12-20 at 09 24 12

**Comment by DarkSnow** [comment]
Do we know if the validate button is picking up the settings from code?

**Comment by joesb** [comment]
Yes, it is, coz the validation response changed after I made the edit at

https://github.com/cabinetoffice/national-leadership-centre-drupal/pull/92/files#diff-a751a19ffcf97ac3e23e7c2d03b56252L21

**Comment by joesb** [comment]
17ed45d now allows s3fs to validate in Drupal s3fs module.

Screenshot 2019-12-20 at 10 28 30

However, seems that we need some extra config in Nginx to support aggregated CSS/JS — cf. https://git.drupalcode.org/project/s3fs/blob/8.x-3.x/README.txt#L141 — and I'm not sure how to do that in Nginx …

… when the bucket name is a dynamic assignment in PaaS, contained in an env var that is a JSON string — can Nginx get an env var, decode JSON and traverse an array to get the bucket name string? Eesh!

**Comment by joesb** [comment]
I think this can be merged, even if it doesn't get to a final fix.

**Pull request merged**
